spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ventas
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.connection-timeout: 60000
    hikari.maximum-pool-size: 5
  thymeleaf:
  cache: false
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
logging:
  level:
    root: INFO
